trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: odidev
      type: github
      endpoint: odidev
      name: odidev/azure-pipeline-templates
      ref: refs/tags/v2.2.0

jobs:
- job: BuildManylinuxWheels
  pool:
    vmImage: ubuntu-18.04
  variables:
    py: /opt/python/cp38-cp38/bin/python
    img: quay.io/pypa/manylinux2014_aarch64
  steps:
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    displayName: Set up QEMU
  - script: |
      docker run --rm -v $(pwd):/ws:rw --workdir=/ws \
      $(img) \
      bash -exc '$(py) -m venv .env && \
      source .env/bin/activate && \
      pip install --upgrade pip wheel && \
      pip wheel --no-deps . -w wheels && \
      for WHL in wheels/*whl; do auditwheel repair ${WHL}; done && \
      deactivate'
    displayName: Build Wheel
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
     
  - task: PublishBuildArtifacts@1
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    inputs:
      pathToPublish: wheels
      artifactName: wheel_linux_aarch64
    displayName: publish wheel artifact
