trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: odidev
      type: github
      endpoint: MyContosoServiceConnection
      name: odidev/azure-pipeline-templates
      ref: refs/tags/v2.2.0

jobs:
- template: job--python-tox.yml@odidev
  parameters:
    toxenvs: [py38]
    os: windows
    coverage: false
    wheel_tags: true
- template: job--python-tox.yml@odidev
  parameters:
    toxenvs: [py38]
    os: macos
    coverage: false
    wheel_tags: true
- template: job--python-tox.yml@odidev
  parameters:
    toxenvs: [py38]
    os: linux
    coverage: false
